Fixed reshaping scripts

diff --git a/AOloopControl/examples/ARTAO-shs-loop-conf/scripts/aorun-005-reshape-fits-to-wfs-pupil b/AOloopControl/examples/ARTAO-shs-loop-conf/scripts/aorun-005-reshape-fits-to-wfs-pupil
--- a/AOloopControl/examples/ARTAO-shs-loop-conf/scripts/aorun-005-reshape-fits-to-wfs-pupil
+++ b/AOloopControl/examples/ARTAO-shs-loop-conf/scripts/aorun-005-reshape-fits-to-wfs-pupil
@@ -34,9 +34,13 @@ FITS_FOLDER=$(dirname "$FITS_PATH")
 FITS_NAME=$(basename "$FITS_PATH")
 echo "Reshaping $FITS_NAME in folder $FITS_FOLDER."
 
+if [ -z "${CACAO_SHSREF_MASK}" ]; then
+	echo "Error: Environment variable $1 is not set."
+	exit 1
+fi
+
 streamcheckOK="OK"
-IMMASK=aol${CACAO_LOOPNUMBER}_shsCam_RefMask
-checkstream $IMMASK
+checkstream ${CACAO_SHSREF_MASK}
 if [ ${streamcheckOK} == "FAIL" ]; then
 	echo "[$(tput setaf 1)$(tput bold) FAILED $(tput sgr0)] stream check failed"
 	exit 1
@@ -74,11 +78,11 @@ loadfits ${FITS_NAME} ${LOCAL_FITS_IM}
 imcpshm ${LOCAL_FITS_IM} ${SHM_FITS_IM}
 
 # Read mask
-readshmim ${IMMASK}
+readshmim ${CACAO_SHSREF_MASK}
 
 # Reshape image
 cacaoio.pupilReshape .linesAsSlices ON
-cacaoio.pupilReshape ${SHM_FITS_IM} ${IMMASK}
+cacaoio.pupilReshape ${SHM_FITS_IM} ${CACAO_SHSREF_MASK}
 
 # Save reshaped image to fits
 readshmim ${SHM_RESHAPE}
diff --git a/AOloopControl/examples/ARTAO-shs-loop-conf/scripts/aorun-010-add-zernike-wfs-offset b/AOloopControl/examples/ARTAO-shs-loop-conf/scripts/aorun-010-add-zernike-wfs-offset
--- a/AOloopControl/examples/ARTAO-shs-loop-conf/scripts/aorun-010-add-zernike-wfs-offset
+++ b/AOloopControl/examples/ARTAO-shs-loop-conf/scripts/aorun-010-add-zernike-wfs-offset
@@ -28,7 +28,6 @@ RequiredPipes=()
 RequiredDirs=()
 
 # Image stream names
-IM_MASK="aol${CACAO_LOOPNUMBER}_shsCam_RefMask"
 ZC_STREAM="aol${CACAO_LOOPNUMBER}_zernCoeff_WFS"
 ZE_1D="aol${CACAO_LOOPNUMBER}_wfszpo" # Output is written to WFS ZPO
 ZE_2D="${ZE_1D}_reshape"
@@ -115,7 +114,13 @@ fi
 
 # Checking mask
 streamcheckOK="OK"
-checkstream ${IM_MASK}
+if [ -z "${CACAO_SHSREF_MASK}" ]; then
+	echo "Error: Environment variable $1 is not set."
+	exit 1
+fi
+
+streamcheckOK="OK"
+checkstream ${CACAO_SHSREF_MASK}
 if [ ${streamcheckOK} == "FAIL" ]; then
 	echo "[$(tput setaf 1)$(tput bold) FAILED $(tput sgr0)] stream check failed"
 	cacaomsglog "ERROR streamcheck - WFS mask does not exist"
@@ -170,12 +175,12 @@ else
 	# Everything good, now expand the coefficients
 MILK_QUIET=1 milk << EOF
 mload cacaoAOloopControlIOtools
-readshmim ${IM_MASK}
+readshmim ${CACAO_SHSREF_MASK}
 readshmim ${ZC_STREAM}
 
 cacaoio.zernikeGen .2Doutput ${reshape}
 
-cacaoio.zernikeGen ${ZC_STREAM} ${IM_MASK} ${ZE_1D}
+cacaoio.zernikeGen ${ZC_STREAM} ${CACAO_SHSREF_MASK} ${ZE_1D}
 
 exit
 EOF
