Intermediate ARTAO setup update

diff --git a/AOloopControl/examples/ARTAO-shs-loop-conf/scripts/aorun-002-take-shs-ref b/AOloopControl/examples/ARTAO-shs-loop-conf/scripts/aorun-002-take-shs-ref
--- a/AOloopControl/examples/ARTAO-shs-loop-conf/scripts/aorun-002-take-shs-ref
+++ b/AOloopControl/examples/ARTAO-shs-loop-conf/scripts/aorun-002-take-shs-ref
@@ -28,10 +28,10 @@ source milk-argparse
 
 # Checking stream
 streamcheckOK="OK"
-checkstream aol${CACAO_LOOPNUMBER}_shsCam
-checkstream aol${CACAO_LOOPNUMBER}_shsCam_AVG
+checkstream ${CACAO_SHSSTREAM}
+checkstream ${CACAO_SHSSTREAM}_AVG
 
-if [ ${streamcheckOK} == "FAIL" ]; then
+if [[ ${streamcheckOK} == "FAIL" ]]; then
 	echo "[$(tput setaf 1)$(tput bold) FAILED $(tput sgr0)] stream check failed"
 	cacaomsglog "ERROR streamcheck"
 	exit 1
@@ -39,28 +39,107 @@ fi
 
 cacaomsglog "NBframe ${NBframe}"
 
-mkdir -p conf
-datestring="$(date -u +'%Y-%m-%dT%H:%M:%S.%NZ')"
-
-
 # Checking FPS
 FPScheckOK="OK"
 checkFPSON CACAO_FPSPROC_SHSONGPU_REF ${CACAO_FPSPROC_SHSONGPU_REF}
 echo "FPScheckOK = ${FPScheckOK}"
 
-if [ ${FPScheckOK} == "FAIL" ]; then
+if [[ ${FPScheckOK} == "FAIL" ]]; then
 	echo "[$(tput setaf 1)$(tput bold) FAILED $(tput sgr0)] FPS check failed"
 	exit 1
 fi
 
 set +e
 
+# == Record reference
 cacaomsglog "START"
 
 sendFPScmd "setval shsOnGPU-Ref-${CACAO_LOOPNUMBER}.procinfo.loopcntMax ${NBframe}"
 sendFPScmd "confwupdate shsOnGPU-Ref-${CACAO_LOOPNUMBER}"
 sendFPScmd "runstart shsOnGPU-Ref-${CACAO_LOOPNUMBER}"
 
+echo "Waiting for completion ..."
+pOK=1
+while [ $pOK -gt 0 ]; do
+	sleep 0.2
+	pOK=$(ps -alx| grep shsOnGPU-Ref-${CACAO_LOOPNUMBER} | grep RUNSTART | wc -l) || :
+done
 
+##### Result management
+# == Save reference to conf dir
+cacaomsglog "Save reference files"
+CONFDIR="./conf/SHSRef" 
+mkdir -p ${CONFDIR}
+
+# Define streamnames
+REF_POS_SHM=${CACAO_SHSSTREAM}_SHSRef_Positions
+REF_MASK_SHM=${CACAO_SHSSTREAM}_SHSRef_Mask
+REF_INT_SHM=${CACAO_SHSSTREAM}_SHSRef_Intensity
+# Define filenames
+REF_POS_FITS="SHSRef_Positions.fits"
+REF_MASK_FITS="SHSRef_Mask.fits"
+REF_INT_FITS="SHSRef_Intensity.fits"
+
+# Save via milk
+MILK_QUIET=1 milk << EOF
+readshmim ${REF_POS_SHM}
+readshmim ${REF_MASK_SHM}
+readshmim ${REF_INT_SHM}
+saveFITS ${REF_POS_SHM} ${REF_POS_FITS}
+saveFITS ${REF_MASK_SHM} ${REF_MASK_FITS}
+saveFITS ${REF_INT_SHM} ${REF_INT_FITS}
+exitCLI
+EOF
+
+# Move files into confdir
+mv ${REF_POS_FITS} "${CONFDIR}/${REF_POS_FITS}"
+mv ${REF_MASK_FITS} "${CONFDIR}/${REF_MASK_FITS}"
+mv ${REF_INT_FITS} "${CONFDIR}/${REF_INT_FITS}"
+
+# == Load reference to freshly named SHM
+# Define loop streams
+CACAO_SHSREF_POS=aol${CACAO_LOOPNUMBER}_shsRef_POS
+CACAO_SHSREF_MASK=aol${CACAO_LOOPNUMBER}_shsRef_MASK
+CACAO_SHSREF_INT=aol${CACAO_LOOPNUMBER}_shsRef_INT
+
+# Function to load a file into shared memory
+load_file_to_shm() {
+    local file="$1"
+    local shm_name="$2"
+
+    echo "Loading file ${file}"
+    if [ -f "${file}" ]; then
+        milk-FITS2shm "${file}" ${shm_name}
+    else
+        echo "Failed to find ${file}."
+        return 1
+    fi
+}
+
+# Load fits files
+rm /milk/shm/*${CACAO_SHSREF_POS}*
+rm /milk/shm/*${CACAO_SHSREF_MASK}*
+rm /milk/shm/*${CACAO_SHSREF_INT}*
+load_file_to_shm "${CONFDIR}/${REF_POS_FITS}" ${CACAO_SHSREF_POS} || exit 1
+load_file_to_shm "${CONFDIR}/${REF_MASK_FITS}" ${CACAO_SHSREF_MASK} || exit 1
+load_file_to_shm "${CONFDIR}/${REF_INT_FITS}" ${CACAO_SHSREF_INT} || exit 1
+
+# == Make reference streamnames accessible in cacao
+CVAR_DIR=${CACAO_LOOPNAME}-rundir/fps.shsOnGPU-Ref-${CACAO_LOOPNUMBER}.datadir
+echo "Exporting cacao variables..."
+echo "export CACAO_SHSREF_POS=${REF_POS_SHM}" > ${CVAR_DIR}/cacaovars.bash
+echo "export CACAO_SHSREF_MASK=${REF_MASK_SHM}" >> ${CVAR_DIR}/cacaovars.bash
+echo "export CACAO_SHSREF_INT=${REF_INT_SHM}" >> ${CVAR_DIR}/cacaovars.bash
+
+# == Log reference
+# Use the stream that includes the cam name for clearness
+
+# The cacaofuncs-log does produce errors (file not found ...)
+# Just copy the conf directory for now.
+cp -r $CONFDIR ./logdir/aol_artao-loop
+#source cacaofuncs-log
+#cacao-calib-logFITSfile ${REF_POS_SHM}
+#cacao-calib-logFITSfile ${REF_MASK_SHM}
+#cacao-calib-logFITSfile ${REF_INT_SHM}
 
 cacaomsglog "END"
diff --git a/AOloopControl/examples/ARTAO-shs-loop-conf/scripts/aorun-003-shs-eval b/AOloopControl/examples/ARTAO-shs-loop-conf/scripts/aorun-003-shs-eval
--- a/AOloopControl/examples/ARTAO-shs-loop-conf/scripts/aorun-003-shs-eval
+++ b/AOloopControl/examples/ARTAO-shs-loop-conf/scripts/aorun-003-shs-eval
@@ -30,18 +30,28 @@ ACTION="${inputMSargARRAY[0]}"
 ACTIONOK=0
 
 
-
 if [ ${ACTION} == "check" ]; then
 	ACTIONOK=1
 fi
+
+# Check for reference variables
+check_variable() {
+    if [ -z "${!1}" ]; then
+        echo "Error: Environment variable $1 is not set."
+        exit 1
+    fi
+}
+check_variable "CACAO_SHSREF_POS"
+check_variable "CACAO_SHSREF_MASK"
+check_variable "CACAO_SHSREF_INT"
 
 # Checking stream
 streamcheckOK="OK"
 checkstream aol${CACAO_LOOPNUMBER}_shsCam
 checkstream aol${CACAO_LOOPNUMBER}_shsCam_AVG
-checkstream aol${CACAO_LOOPNUMBER}_shsCam_RefPositions
-checkstream aol${CACAO_LOOPNUMBER}_shsCam_RefMask
-checkstream aol${CACAO_LOOPNUMBER}_shsCam_RefIntensity
+checkstream $CACAO_SHSREF_POS
+checkstream $CACAO_SHSREF_MASK
+checkstream $CACAO_SHSREF_INT
 
 if [ ${streamcheckOK} == "FAIL" ]; then
 	echo "[$(tput setaf 1)$(tput bold) FAILED $(tput sgr0)] stream check failed"
@@ -61,7 +71,6 @@ fi
 
 set +e
 shsEvalRunning=0
-echo "${CACAO_LOOPNUMBER}"
 echo "Check if evaluation process is running. An error message will apear if it doesn't - that's expected."
 pOK=$(ps -alx| grep shsOnGPU-Eval-${CACAO_LOOPNUMBER} | grep RUNSTART | wc -l)
 if [ $pOK -gt 0 ]; then
@@ -81,6 +90,9 @@ if [ ${ACTION} == "start" ]; then
 	# Starting SHS evaluation process
 	# ======================================================================
 	if [ ${shsEvalRunning} == "0" ]; then
+		sendFPScmd "setval shsOnGPU-Eval-${CACAO_LOOPNUMBER}.reference.position ${CACAO_SHSREF_POS}"
+		sendFPScmd "setval shsOnGPU-Eval-${CACAO_LOOPNUMBER}.reference.mask ${CACAO_SHSREF_MASK}"
+		sendFPScmd "setval shsOnGPU-Eval-${CACAO_LOOPNUMBER}.reference.intensity ${CACAO_SHSREF_INT}"
 		sendFPScmd "confwupdate shsOnGPU-Eval-${CACAO_LOOPNUMBER}"
 		sendFPScmd "runstart shsOnGPU-Eval-${CACAO_LOOPNUMBER}"
 	else
diff --git a/AOloopControl/examples/ARTAO-shs-loop-conf/scripts/aorun-004-reshape-to-wfs-pupil b/AOloopControl/examples/ARTAO-shs-loop-conf/scripts/aorun-004-reshape-to-wfs-pupil
--- a/AOloopControl/examples/ARTAO-shs-loop-conf/scripts/aorun-004-reshape-to-wfs-pupil
+++ b/AOloopControl/examples/ARTAO-shs-loop-conf/scripts/aorun-004-reshape-to-wfs-pupil
@@ -18,8 +18,6 @@ These are defined according to the wfs pupil mask.
 source milk-script-std-config
 source cacao-check-cacaovars
 
-IM_MASK="aol${CACAO_LOOPNUMBER}_shsCam_RefMask"
-
 # prerequisites
 #
 RequiredCommands=( milk )
@@ -70,7 +68,13 @@ fi
 # Checking FPS & Image Streams
 # Checking stream
 streamcheckOK="OK"
-checkstream ${IM_MASK}
+
+if [ -z "${CACAO_SHSREF_MASK}" ]; then
+	echo "Error: Environment variable $1 is not set."
+	exit 1
+fi
+
+checkstream ${CACAO_SHSREF_MASK}
 
 FPScheckOK="OK"
 case "${STREAMOPT}" in
@@ -155,7 +159,7 @@ if [ ${ACTION} == "start" ]; then
 		fi
 
 		sendFPScmd "setval ${FPSNAME}.input_name ${IMNAME}"
-		sendFPScmd "setval ${FPSNAME}.mask_name ${IM_MASK}"
+		sendFPScmd "setval ${FPSNAME}.mask_name ${CACAO_SHSREF_MASK}"
 		sendFPScmd "confwupdate ${FPSNAME}"
 		sendFPScmd "runstart ${FPSNAME}"
 	else
