Implemented measurement of CMode latencies based on DM pokes and WFS responses from the CM.

diff --git a/AOloopControl/examples/ARTAO-shs-loop-conf/scripts/aorun-008-measure-dm-mode-latencies b/AOloopControl/examples/ARTAO-shs-loop-conf/scripts/aorun-008-measure-dm-mode-latencies
--- a/AOloopControl/examples/ARTAO-shs-loop-conf/scripts/aorun-008-measure-dm-mode-latencies
+++ b/AOloopControl/examples/ARTAO-shs-loop-conf/scripts/aorun-008-measure-dm-mode-latencies
@@ -20,6 +20,7 @@ source milk-script-std-config
 source cacao-check-cacaovars
 
 MSarg+=( "pokePatternStream:string:pokePatternStream" )
+MSarg+=( "pokeResponseStream:string:pokeResponseStream" )
 
 NBpatterns="-1"
 MSopt+=( "n:nbpatterns:set_NBpatterns:nbpatterns[long]:set number of patterns to poke (-1=all)" )
@@ -30,9 +31,15 @@ function set_NBpatterns() {
 source milk-argparse
 
 PATTERN_STREAM="${inputMSargARRAY[0]}"
+RESPONSE_STREAM="${inputMSargARRAY[1]}"
 
 streamcheckOK="OK"
 checkstream $PATTERN_STREAM
+if [ ${streamcheckOK} == "FAIL" ]; then
+	echo "[$(tput setaf 1)$(tput bold) FAILED $(tput sgr0)] stream check failed"
+	exit 1
+fi
+checkstream $RESPONSE_STREAM
 if [ ${streamcheckOK} == "FAIL" ]; then
 	echo "[$(tput setaf 1)$(tput bold) FAILED $(tput sgr0)] stream check failed"
 	exit 1
@@ -68,8 +75,10 @@ else
 fi
 
 sendFPScmd "setval mlat-slowDM-${CACAO_LOOPNUMBER}.skipFramerateMeas ON"
-sendFPScmd "setval mlat-slowDM-${CACAO_LOOPNUMBER}.pokePattern -1"
-sendFPScmd "setval mlat-slowDM-${CACAO_LOOPNUMBER}.patternStream ${PATTERN_STREAM}"
+sendFPScmd "setval mlat-slowDM-${CACAO_LOOPNUMBER}.pattern.type -1"
+sendFPScmd "setval mlat-slowDM-${CACAO_LOOPNUMBER}.pattern.customPokeStream ${PATTERN_STREAM}"
+sendFPScmd "setval mlat-slowDM-${CACAO_LOOPNUMBER}.pattern.useCustomResponse ON"
+sendFPScmd "setval mlat-slowDM-${CACAO_LOOPNUMBER}.pattern.customResponseStream ${RESPONSE_STREAM}"
 
 echo $OUTPUT_FILE
 echo \
@@ -87,7 +96,8 @@ echo \
 # For each pattern ...
 for (( Pidx=0; Pidx<NUM_ITERATIONS; Pidx++ )); do
     echo "Measuring latency for pattern number $Pidx ..."
-    sendFPScmd "setval mlat-slowDM-${CACAO_LOOPNUMBER}.shmImPatterIdx ${Pidx}"
+    sendFPScmd "setval mlat-slowDM-${CACAO_LOOPNUMBER}.pattern.customPatternIdx ${Pidx}"
+    sendFPScmd "setval mlat-slowDM-${CACAO_LOOPNUMBER}.pattern.customResponseIdx ${Pidx}"
     cacao-aorun-021-mlat-slowDM -w
     source $SRCDIR/cacaovars.bash
     echo -e \
